module.exports = {
  tag: require('./lib/tag'),
  size: require('./lib/size'),
  sample: require('./lib/sample'),
  jenks: require('./lib/jenks'),
  quantile: require('./lib/quantile'),
  save: require('./lib/save'),
  envelope: require('./lib/envelope'),
  square: require('./lib/square'),
  midpoint: require('./lib/midpoint'),
  buffer: require('./lib/buffer'),
  center: require('./lib/center'),
  centroid: require('./lib/centroid'),
  combine: require('./lib/combine'),
  contour: require('./lib/contour'),
  distance: require('./lib/distance'),
  explode: require('./lib/explode'),
  extent: require('./lib/extent'),
  bboxPolygon: require('./lib/bboxPolygon'),
  featurecollection: require('./lib/featurecollection'),
  filter: require('./lib/filter'),
  grid: require('./lib/grid'),
  inside: require('./lib/inside'),
  intersect: require('./lib/intersect'),
  linestring: require('./lib/linestring'),
  load: require('./lib/load'),
  nearest: require('./lib/nearest'),
  planepoint: require('./lib/planepoint'),
  point: require('./lib/point'),
  polygon: require('./lib/polygon'),
  quantile: require('./lib/quantile'),
  reclass: require('./lib/reclass'),
  remove: require('./lib/remove'),
  tin: require('./lib/tin'),
  union: require('./lib/union')
}

