packages:
  - "packages/*"
  - "test/*"

allowBuilds:
  esbuild: false
  nx: false

catalog:
  "@types/benchmark": ^2.1.5
  "@types/geojson": ^7946.0.10
  "@types/tape": ^5.8.1
  benchmark: ^2.1.4
  tape: ^5.10.2
  tstyche: ^6.2.0
  tsx: ^4.22.4
  typescript: ^6.0.3

catalogs:
  # keep a named catalog of typescript@5 for the consumer tests
  typescript5:
    typescript: 5.9.3

overrides:
  # we do not use the vue capabilities of documentation, so remove this optional dependency
  # which has a (false positive) CVE associated with it
  "documentation>vue-template-compiler": "-"
