cd /Users/mac/Github/turf-upgrade-dev/packages/turf-area && yarn add --dev tape benchmark
cd /Users/mac/Github/turf-upgrade-dev/packages/turf-bbox && yarn add --dev tape benchmark
cd /Users/mac/Github/turf-upgrade-dev/packages/turf-bbox-clip && yarn add --dev tape benchmark
cd /Users/mac/Github/turf-upgrade-dev/packages/turf-bbox-polygon && yarn add --dev tape benchmark
cd /Users/mac/Github/turf-upgrade-dev/packages/turf-bearing && yarn add --dev tape benchmark
cd /Users/mac/Github/turf-upgrade-dev/packages/turf-bezier && yarn add --dev tape benchmark
cd /Users/mac/Github/turf-upgrade-dev/packages/turf-buffer && yarn add --dev tape benchmark
cd /Users/mac/Github/turf-upgrade-dev/packages/turf-center && yarn add --dev tape benchmark
cd /Users/mac/Github/turf-upgrade-dev/packages/turf-center-of-mass && yarn add --dev tape benchmark
cd /Users/mac/Github/turf-upgrade-dev/packages/turf-centroid && yarn add --dev tape benchmark
cd /Users/mac/Github/turf-upgrade-dev/packages/turf-circle && yarn add --dev tape benchmark
cd /Users/mac/Github/turf-upgrade-dev/packages/turf-collect && yarn add --dev tape benchmark
cd /Users/mac/Github/turf-upgrade-dev/packages/turf-combine && yarn add --dev tape benchmark
cd /Users/mac/Github/turf-upgrade-dev/packages/turf-concave && yarn add --dev tape benchmark
cd /Users/mac/Github/turf-upgrade-dev/packages/turf-convex && yarn add --dev tape benchmark
cd /Users/mac/Github/turf-upgrade-dev/packages/turf-destination && yarn add --dev tape benchmark
cd /Users/mac/Github/turf-upgrade-dev/packages/turf-difference && yarn add --dev tape benchmark
cd /Users/mac/Github/turf-upgrade-dev/packages/turf-dissolve && yarn add --dev tape benchmark
cd /Users/mac/Github/turf-upgrade-dev/packages/turf-distance && yarn add --dev tape benchmark
cd /Users/mac/Github/turf-upgrade-dev/packages/turf-envelope && yarn add --dev tape benchmark
cd /Users/mac/Github/turf-upgrade-dev/packages/turf-explode && yarn add --dev tape benchmark
cd /Users/mac/Github/turf-upgrade-dev/packages/turf-flatten && yarn add --dev tape benchmark
cd /Users/mac/Github/turf-upgrade-dev/packages/turf-flip && yarn add --dev tape benchmark
cd /Users/mac/Github/turf-upgrade-dev/packages/turf-great-circle && yarn add --dev tape benchmark
cd /Users/mac/Github/turf-upgrade-dev/packages/turf-helpers && yarn add --dev tape benchmark
cd /Users/mac/Github/turf-upgrade-dev/packages/turf-hex-grid && yarn add --dev tape benchmark
cd /Users/mac/Github/turf-upgrade-dev/packages/turf-idw && yarn add --dev tape benchmark
cd /Users/mac/Github/turf-upgrade-dev/packages/turf-inside && yarn add --dev tape benchmark
cd /Users/mac/Github/turf-upgrade-dev/packages/turf-intersect && yarn add --dev tape benchmark
cd /Users/mac/Github/turf-upgrade-dev/packages/turf-invariant && yarn add --dev tape benchmark
cd /Users/mac/Github/turf-upgrade-dev/packages/turf-isobands && yarn add --dev tape benchmark
cd /Users/mac/Github/turf-upgrade-dev/packages/turf-isolines && yarn add --dev tape benchmark
cd /Users/mac/Github/turf-upgrade-dev/packages/turf-kinks && yarn add --dev tape benchmark
cd /Users/mac/Github/turf-upgrade-dev/packages/turf-line-arc && yarn add --dev tape benchmark
cd /Users/mac/Github/turf-upgrade-dev/packages/turf-line-chunk && yarn add --dev tape benchmark
cd /Users/mac/Github/turf-upgrade-dev/packages/turf-line-distance && yarn add --dev tape benchmark
cd /Users/mac/Github/turf-upgrade-dev/packages/turf-line-intersect && yarn add --dev tape benchmark
cd /Users/mac/Github/turf-upgrade-dev/packages/turf-line-overlap && yarn add --dev tape benchmark
cd /Users/mac/Github/turf-upgrade-dev/packages/turf-line-segment && yarn add --dev tape benchmark
cd /Users/mac/Github/turf-upgrade-dev/packages/turf-line-slice && yarn add --dev tape benchmark
cd /Users/mac/Github/turf-upgrade-dev/packages/turf-line-slice-along && yarn add --dev tape benchmark
cd /Users/mac/Github/turf-upgrade-dev/packages/turf-line-split && yarn add --dev tape benchmark
cd /Users/mac/Github/turf-upgrade-dev/packages/turf-linestring-to-polygon && yarn add --dev tape benchmark
cd /Users/mac/Github/turf-upgrade-dev/packages/turf-mask && yarn add --dev tape benchmark
cd /Users/mac/Github/turf-upgrade-dev/packages/turf-meta && yarn add --dev tape benchmark
cd /Users/mac/Github/turf-upgrade-dev/packages/turf-midpoint && yarn add --dev tape benchmark
cd /Users/mac/Github/turf-upgrade-dev/packages/turf-nearest && yarn add --dev tape benchmark
cd /Users/mac/Github/turf-upgrade-dev/packages/turf-planepoint && yarn add --dev tape benchmark
cd /Users/mac/Github/turf-upgrade-dev/packages/turf-point-grid && yarn add --dev tape benchmark
cd /Users/mac/Github/turf-upgrade-dev/packages/turf-point-on-line && yarn add --dev tape benchmark
cd /Users/mac/Github/turf-upgrade-dev/packages/turf-point-on-surface && yarn add --dev tape benchmark
cd /Users/mac/Github/turf-upgrade-dev/packages/turf-polygon-tangents && yarn add --dev tape benchmark
cd /Users/mac/Github/turf-upgrade-dev/packages/turf-polygon-to-linestring && yarn add --dev tape benchmark
cd /Users/mac/Github/turf-upgrade-dev/packages/turf-random && yarn add --dev tape benchmark
cd /Users/mac/Github/turf-upgrade-dev/packages/turf-rewind && yarn add --dev tape benchmark
cd /Users/mac/Github/turf-upgrade-dev/packages/turf-sample && yarn add --dev tape benchmark
cd /Users/mac/Github/turf-upgrade-dev/packages/turf-sector && yarn add --dev tape benchmark
cd /Users/mac/Github/turf-upgrade-dev/packages/turf-simplify && yarn add --dev tape benchmark
cd /Users/mac/Github/turf-upgrade-dev/packages/turf-square && yarn add --dev tape benchmark
cd /Users/mac/Github/turf-upgrade-dev/packages/turf-square-grid && yarn add --dev tape benchmark
cd /Users/mac/Github/turf-upgrade-dev/packages/turf-tag && yarn add --dev tape benchmark
cd /Users/mac/Github/turf-upgrade-dev/packages/turf-tesselate && yarn add --dev tape benchmark
cd /Users/mac/Github/turf-upgrade-dev/packages/turf-tin && yarn add --dev tape benchmark
cd /Users/mac/Github/turf-upgrade-dev/packages/turf-triangle-grid && yarn add --dev tape benchmark
cd /Users/mac/Github/turf-upgrade-dev/packages/turf-truncate && yarn add --dev tape benchmark
cd /Users/mac/Github/turf-upgrade-dev/packages/turf-union && yarn add --dev tape benchmark
cd /Users/mac/Github/turf-upgrade-dev/packages/turf-unkink-polygon && yarn add --dev tape benchmark
cd /Users/mac/Github/turf-upgrade-dev/packages/turf-within && yarn add --dev tape benchmark
