name: Publish release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  id-token: write
  contents: write

jobs:
  publish:
    name: "Publish Release"
    environment: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: pnpm/setup
        uses: pnpm/setup@703c52620218391530e48b9e8870d5c0082e1b9b # v2.1.0
        with:
          runtime: node@26
          require-lockfile: true
          cache: false

      - run: pnpm build
      - run: pnpm test

      - name: run publish
        run: pnpm -r publish --no-git-checks --provenance --access public

      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${GITHUB_REF_NAME}" \
            --verify-tag \
            --fail-on-no-commits \
            --draft \
            --generate-notes \
            --latest
