name: Publish release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  id-token: write
  contents: write

jobs:
  publish:
    name: "Publish Release"
    environment: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install pnpm
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
        with:
          run_install: false

      - name: Use Node.js 26
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: "26"
          registry-url: "https://registry.npmjs.org"
          package-manager-cache: false

      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - run: pnpm test

      - name: run publish
        run: pnpm -r publish --no-git-checks --provenance --access public

      - name: Create Github Release
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # 3.0.2
        with:
          make_latest: true
          generate_release_notes: true
          draft: true
